[profile.default]
optimizer = true
optimizer_runs = 44_444_444
via_ir = true
ffi = true
fs_permissions = [
    { access = 'read', path = './'},
    { access = 'read-write', path = './script/config' }
]
verbosity = 3

[fmt]
line_length = 100
tab_width = 2
quote_style = 'single'
number_underscore = 'thousands'
sort_imports = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
