name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Foundry build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: KyberNetwork/foundry-toolchain@master

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build
